providers = ["node"]
[variables]
  # Node environment parameter override
  NODE_ENV = 'production'
  # Prisma flag to install the right engines
  PRISMA_CLI_QUERY_ENGINE_TYPE = 'binary'

[phases.install]
  # Usa npm de acordo com o package-lock.json
  cmd = 'npm ci'

[phases.build]
  # Comandos declarados no backend que farão a build do NestJS e gerarão as tipagens do client prisma
  cmd = 'npm run build'

[start]
  # Script do package.json que agora contém (npx prisma migrate deploy && node dist/main)
  cmd = 'npm run start:prod'
