[providers]
  # Força a compilação utilizando o provider node
  node = {}

[variables]
  # Node environment parameter override
  NODE_ENV = 'production'
  # Prisma flag to install the right engines
  PRISMA_CLI_QUERY_ENGINE_TYPE = 'binary'

[phases.install]
  # Comando Pnpm padrão para instalar libs nativamente
  cmd = 'pnpm install'

[phases.build]
  # Comandos declarados no backend que farão a build do NestJS e gerarão as tipagens do client prisma
  cmd = 'pnpm run build'

[start]
  # Script do package.json que agora contém (npx prisma migrate deploy && node dist/main)
  cmd = 'pnpm run start:prod'
